//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.05 at 04:59:49 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://megatravel.com/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.MegaTravel_XML.model.user;
