version: '3'
services:

  eureka:
    image: eureka-service
    container_name: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  zuul:
    image: zuul-service
    container_name: zuul-service
    build:
      context: ./zuul-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - eureka
    links:
      - eureka:eureka

  agent:
    image: agent
    container_name: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8081"
    depends_on:
      - eureka
    links:
      - eureka:eureka