//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 11:15:23 PM CEST 
//


package com.example.authservice.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.MegaTravel_XML.new_model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserId_QNAME = new QName("http://megatravel.com/user", "id");
    private final static QName _UserName_QNAME = new QName("http://megatravel.com/user", "name");
    private final static QName _UserEmail_QNAME = new QName("http://megatravel.com/user", "email");
    private final static QName _UserEnabled_QNAME = new QName("http://megatravel.com/user", "enabled");
    private final static QName _UserRole_QNAME = new QName("http://megatravel.com/user", "role");
    private final static QName _UserDeleted_QNAME = new QName("http://megatravel.com/user", "deleted");
    private final static QName _UserLastPasswordResetDate_QNAME = new QName("http://megatravel.com/user", "lastPasswordResetDate");
    private final static QName _UserSurname_QNAME = new QName("http://megatravel.com/user", "surname");
    private final static QName _UserPasssword_QNAME = new QName("http://megatravel.com/user", "passsword");
    private final static QName _UserBlocked_QNAME = new QName("http://megatravel.com/user", "blocked");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.MegaTravel_XML.new_model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
    public Administrator createAdministrator() {
        return new Administrator();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link AccomodationResponse }
     * 
     */
    public AccomodationResponse createAccomodationResponse() {
        return new AccomodationResponse();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link AdditionalService }
     * 
     */
    public AdditionalService createAdditionalService() {
        return new AdditionalService();
    }

    /**
     * Create an instance of {@link Cancelation }
     * 
     */
    public Cancelation createCancelation() {
        return new Cancelation();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link PriceForNight }
     * 
     */
    public PriceForNight createPriceForNight() {
        return new PriceForNight();
    }

    /**
     * Create an instance of {@link AccomodationRequest }
     * 
     */
    public AccomodationRequest createAccomodationRequest() {
        return new AccomodationRequest();
    }

    /**
     * Create an instance of {@link RoomResponse }
     * 
     */
    public RoomResponse createRoomResponse() {
        return new RoomResponse();
    }

    /**
     * Create an instance of {@link RoomRequest }
     * 
     */
    public RoomRequest createRoomRequest() {
        return new RoomRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "id", scope = User.class)
    public JAXBElement<Long> createUserId(Long value) {
        return new JAXBElement<Long>(_UserId_QNAME, Long.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "name", scope = User.class)
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "email", scope = User.class)
    public JAXBElement<String> createUserEmail(String value) {
        return new JAXBElement<String>(_UserEmail_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "enabled", scope = User.class)
    public JAXBElement<Boolean> createUserEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_UserEnabled_QNAME, Boolean.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "role", scope = User.class)
    public JAXBElement<String> createUserRole(String value) {
        return new JAXBElement<String>(_UserRole_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "deleted", scope = User.class)
    public JAXBElement<Boolean> createUserDeleted(Boolean value) {
        return new JAXBElement<Boolean>(_UserDeleted_QNAME, Boolean.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "lastPasswordResetDate", scope = User.class)
    public JAXBElement<XMLGregorianCalendar> createUserLastPasswordResetDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UserLastPasswordResetDate_QNAME, XMLGregorianCalendar.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "surname", scope = User.class)
    public JAXBElement<String> createUserSurname(String value) {
        return new JAXBElement<String>(_UserSurname_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "passsword", scope = User.class)
    public JAXBElement<String> createUserPasssword(String value) {
        return new JAXBElement<String>(_UserPasssword_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "blocked", scope = User.class)
    public JAXBElement<Boolean> createUserBlocked(Boolean value) {
        return new JAXBElement<Boolean>(_UserBlocked_QNAME, Boolean.class, User.class, value);
    }

}
