//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 11:01:54 PM CEST 
//


package com.example.agent.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.MegaTravel_XML.model.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserId_QNAME = new QName("http://megatravel.com/user", "id");
    private final static QName _UserName_QNAME = new QName("http://megatravel.com/user", "name");
    private final static QName _UserEmail_QNAME = new QName("http://megatravel.com/user", "email");
    private final static QName _UserEnabled_QNAME = new QName("http://megatravel.com/user", "enabled");
    private final static QName _UserRole_QNAME = new QName("http://megatravel.com/user", "role");
    private final static QName _UserDeleted_QNAME = new QName("http://megatravel.com/user", "deleted");
    private final static QName _UserLastPasswordResetDate_QNAME = new QName("http://megatravel.com/user", "lastPasswordResetDate");
    private final static QName _UserSurname_QNAME = new QName("http://megatravel.com/user", "surname");
    private final static QName _UserPasssword_QNAME = new QName("http://megatravel.com/user", "passsword");
    private final static QName _UserBlocked_QNAME = new QName("http://megatravel.com/user", "blocked");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.MegaTravel_XML.model.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveMessageResponse }
     * 
     */
    public SaveMessageResponse createSaveMessageResponse() {
        return new SaveMessageResponse();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link GetAddressResponse }
     * 
     */
    public GetAddressResponse createGetAddressResponse() {
        return new GetAddressResponse();
    }

    /**
     * Create an instance of {@link SaveRoomRequest }
     * 
     */
    public SaveRoomRequest createSaveRoomRequest() {
        return new SaveRoomRequest();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link PriceForNight }
     * 
     */
    public PriceForNight createPriceForNight() {
        return new PriceForNight();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link AdditionalService }
     * 
     */
    public AdditionalService createAdditionalService() {
        return new AdditionalService();
    }

    /**
     * Create an instance of {@link Cancelation }
     * 
     */
    public Cancelation createCancelation() {
        return new Cancelation();
    }

    /**
     * Create an instance of {@link GetPriceResponse }
     * 
     */
    public GetPriceResponse createGetPriceResponse() {
        return new GetPriceResponse();
    }

    /**
     * Create an instance of {@link GetRoomResponse }
     * 
     */
    public GetRoomResponse createGetRoomResponse() {
        return new GetRoomResponse();
    }

    /**
     * Create an instance of {@link SaveReservationRequest }
     * 
     */
    public SaveReservationRequest createSaveReservationRequest() {
        return new SaveReservationRequest();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceResponse }
     * 
     */
    public GetAdditionalServiceResponse createGetAdditionalServiceResponse() {
        return new GetAdditionalServiceResponse();
    }

    /**
     * Create an instance of {@link GetAdditionalServiceRequest }
     * 
     */
    public GetAdditionalServiceRequest createGetAdditionalServiceRequest() {
        return new GetAdditionalServiceRequest();
    }

    /**
     * Create an instance of {@link SaveRoomResponse }
     * 
     */
    public SaveRoomResponse createSaveRoomResponse() {
        return new SaveRoomResponse();
    }

    /**
     * Create an instance of {@link GetAgentResponse }
     * 
     */
    public GetAgentResponse createGetAgentResponse() {
        return new GetAgentResponse();
    }

    /**
     * Create an instance of {@link GetClientRequest }
     * 
     */
    public GetClientRequest createGetClientRequest() {
        return new GetClientRequest();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link GetPriceRequest }
     * 
     */
    public GetPriceRequest createGetPriceRequest() {
        return new GetPriceRequest();
    }

    /**
     * Create an instance of {@link SaveReservationResponse }
     * 
     */
    public SaveReservationResponse createSaveReservationResponse() {
        return new SaveReservationResponse();
    }

    /**
     * Create an instance of {@link GetCommentResponse }
     * 
     */
    public GetCommentResponse createGetCommentResponse() {
        return new GetCommentResponse();
    }

    /**
     * Create an instance of {@link GetMessageRequest }
     * 
     */
    public GetMessageRequest createGetMessageRequest() {
        return new GetMessageRequest();
    }

    /**
     * Create an instance of {@link GetCommentRequest }
     * 
     */
    public GetCommentRequest createGetCommentRequest() {
        return new GetCommentRequest();
    }

    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link GetClientResponse }
     * 
     */
    public GetClientResponse createGetClientResponse() {
        return new GetClientResponse();
    }

    /**
     * Create an instance of {@link GetAddressRequest }
     * 
     */
    public GetAddressRequest createGetAddressRequest() {
        return new GetAddressRequest();
    }

    /**
     * Create an instance of {@link SaveMessageRequest }
     * 
     */
    public SaveMessageRequest createSaveMessageRequest() {
        return new SaveMessageRequest();
    }

    /**
     * Create an instance of {@link GetCancelationResponse }
     * 
     */
    public GetCancelationResponse createGetCancelationResponse() {
        return new GetCancelationResponse();
    }

    /**
     * Create an instance of {@link GetRoleRequest }
     * 
     */
    public GetRoleRequest createGetRoleRequest() {
        return new GetRoleRequest();
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationTypeResponse }
     * 
     */
    public GetAccommodationTypeResponse createGetAccommodationTypeResponse() {
        return new GetAccommodationTypeResponse();
    }

    /**
     * Create an instance of {@link GetCancelationRequest }
     * 
     */
    public GetCancelationRequest createGetCancelationRequest() {
        return new GetCancelationRequest();
    }

    /**
     * Create an instance of {@link GetPermissionResponse }
     * 
     */
    public GetPermissionResponse createGetPermissionResponse() {
        return new GetPermissionResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationRequest }
     * 
     */
    public GetAccommodationRequest createGetAccommodationRequest() {
        return new GetAccommodationRequest();
    }

    /**
     * Create an instance of {@link GetRoleResponse }
     * 
     */
    public GetRoleResponse createGetRoleResponse() {
        return new GetRoleResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationResponse }
     * 
     */
    public GetAccommodationResponse createGetAccommodationResponse() {
        return new GetAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetPermissionRequest }
     * 
     */
    public GetPermissionRequest createGetPermissionRequest() {
        return new GetPermissionRequest();
    }

    /**
     * Create an instance of {@link GetRoomRequest }
     * 
     */
    public GetRoomRequest createGetRoomRequest() {
        return new GetRoomRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationTypeRequest }
     * 
     */
    public GetAccommodationTypeRequest createGetAccommodationTypeRequest() {
        return new GetAccommodationTypeRequest();
    }

    /**
     * Create an instance of {@link AccomodationResponse }
     * 
     */
    public AccomodationResponse createAccomodationResponse() {
        return new AccomodationResponse();
    }

    /**
     * Create an instance of {@link AccomodationRequest }
     * 
     */
    public AccomodationRequest createAccomodationRequest() {
        return new AccomodationRequest();
    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
    public Administrator createAdministrator() {
        return new Administrator();
    }

    /**
     * Create an instance of {@link RoomResponse }
     * 
     */
    public RoomResponse createRoomResponse() {
        return new RoomResponse();
    }

    /**
     * Create an instance of {@link RoomRequest }
     * 
     */
    public RoomRequest createRoomRequest() {
        return new RoomRequest();
    }

    /**
     * Create an instance of {@link MessageRequest }
     * 
     */
    public MessageRequest createMessageRequest() {
        return new MessageRequest();
    }

    /**
     * Create an instance of {@link MessageResponse }
     * 
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link ReservationResponse }
     * 
     */
    public ReservationResponse createReservationResponse() {
        return new ReservationResponse();
    }

    /**
     * Create an instance of {@link ReservationRequest }
     * 
     */
    public ReservationRequest createReservationRequest() {
        return new ReservationRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "id", scope = User.class)
    public JAXBElement<Long> createUserId(Long value) {
        return new JAXBElement<Long>(_UserId_QNAME, Long.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "name", scope = User.class)
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "email", scope = User.class)
    public JAXBElement<String> createUserEmail(String value) {
        return new JAXBElement<String>(_UserEmail_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "enabled", scope = User.class)
    public JAXBElement<Boolean> createUserEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_UserEnabled_QNAME, Boolean.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "role", scope = User.class)
    public JAXBElement<String> createUserRole(String value) {
        return new JAXBElement<String>(_UserRole_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "deleted", scope = User.class)
    public JAXBElement<Boolean> createUserDeleted(Boolean value) {
        return new JAXBElement<Boolean>(_UserDeleted_QNAME, Boolean.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "lastPasswordResetDate", scope = User.class)
    public JAXBElement<XMLGregorianCalendar> createUserLastPasswordResetDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UserLastPasswordResetDate_QNAME, XMLGregorianCalendar.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "surname", scope = User.class)
    public JAXBElement<String> createUserSurname(String value) {
        return new JAXBElement<String>(_UserSurname_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "passsword", scope = User.class)
    public JAXBElement<String> createUserPasssword(String value) {
        return new JAXBElement<String>(_UserPasssword_QNAME, String.class, User.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://megatravel.com/user", name = "blocked", scope = User.class)
    public JAXBElement<Boolean> createUserBlocked(Boolean value) {
        return new JAXBElement<Boolean>(_UserBlocked_QNAME, Boolean.class, User.class, value);
    }

}
