FROM anapsix/alpine-java
MAINTAINER Andrijana Jeremic <andrijana.jeremi@gmail.com>
ADD target/MegaTravel_XML-0.0.1-SNAPSHOT.jar MegaTravel_XML.jar
ENTRYPOINT ["java", "-jar", "/MegaTravel_XML.jar"]
EXPOSE 8080